name: CI
on:
  pull_request:
  push:
    branches:
      - main
env:
  RUST_BACKTRACE: 1

jobs:
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - check-test-all
    steps:
      - run: exit 0

  build-nostds:
    name: Build on no_std target (thumbv7em-none-eabi)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - crate: codex-percent
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: thumbv7em-none-eabi
      - uses: taiki-e/install-action@cargo-hack
      # No default features build
      - name: no_std / encoder-fixed
        run: cargo build -p ${{ matrix.crate }} --target thumbv7em-none-eabi --release --no-default-features --features encode,fixed
      - name: no_std / decoder-fixed
        run: cargo build -p ${{ matrix.crate }} --target thumbv7em-none-eabi --release --no-default-features --features decode,fixed
      - name: no_std / decoder-vec
        run: cargo build -p ${{ matrix.crate }} --target thumbv7em-none-eabi --release --no-default-features --features decode,vec
      - name: no_std / encoder-vec
        run: cargo build -p ${{ matrix.crate }} --target thumbv7em-none-eabi --release --no-default-features --features encode,vec

  check-test-all:
    name: test, fmt, clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - run: cargo test --all-features
      - run: cargo fmt --check
      - run: cargo clippy
      - run: cargo doc
